### ISSUE TITLE
Missing options.yml file on default distribution

### ISSUE THREAD

**Issue by Nordicdesign** [area17/subfolio#2]
I had an issue with folders and files not appearing using the default sharing mode. I [followed the instructions](http://area17.github.io/subfolio/#installation-installing), but the 1-minute installation omits a key step, to have a default's theme 'options.yml'.

Your distribution only includes the sample, not that file.

**Comment by davidprati** [comment]
I have the same problem.

**Comment by nedbaldessin** [comment]
Yes, it's a convention to have `foobar.sample.yml` files in source control, and have the user create `foobar.yml` file, that will be ignored by source control.

Sorry that wasn't made clear in the documentation.
