### ISSUE TITLE
Hashing passwords

### ISSUE THREAD

**Issue by Nordicdesign** [area17/subfolio#5]
The site http://www.yoursite.com/hash/yourpassword does not exist anymore, and I don't know how to hash my password. Tried with MD5 but it doesn't work.

**Comment by nedbaldessin** [comment]
Maybe this was miscommunicated in the documentation, but "www.yoursite.com" should be replaced by the domain you just installed Subfolio on (e.g http://www.nordicdesign.com/hash/foobar).

:)
